"""empty message

Revision ID: 3e570e27eec0
Revises: 
Create Date: 2020-08-27 08:43:34.994200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e570e27eec0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=129), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name'),
    sa.UniqueConstraint('id')
    )
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('true_name', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.Enum('男', '女', '保密'), nullable=True),
    sa.Column('birthday', sa.DateTime(), nullable=True),
    sa.Column('tel', sa.String(length=11), nullable=True),
    sa.Column('mail', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('head_url', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('tel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('blog')
    op.drop_table('account')
    # ### end Alembic commands ###
