"""empty message

Revision ID: a27d622cb3a8
Revises: 3e570e27eec0
Create Date: 2020-08-27 14:33:31.839651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27d622cb3a8'
down_revision = '3e570e27eec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'account_id')
    # ### end Alembic commands ###
