"""empty message

Revision ID: ce902c5ba9a1
Revises: fa699ce46b40
Create Date: 2020-08-24 17:30:02.091624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ce902c5ba9a1'
down_revision = 'fa699ce46b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=129), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_name'),
    sa.UniqueConstraint('id')
    )
    op.add_column('user', sa.Column('true_name', sa.String(length=32), nullable=True))
    op.drop_index('name', table_name='user')
    op.drop_column('user', 'password')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=129), nullable=True))
    op.create_index('name', 'user', ['name'], unique=True)
    op.drop_column('user', 'true_name')
    op.drop_table('account')
    # ### end Alembic commands ###
